base: config/base_epoch.yml

model:
  backbone: resnet50
  pooling: gem_pooling
  head: BNHead
  bn_where: after

data:
  name: ppe_two
  batch_size: 32

optimizer:
  name: sgd
  lr: 0.01
  specified_lr:
    enable: True
    lr: 0.1
    layers: [head]

loss:
  name: CEL_Sigmoid

freeze:
  enable: True
  layers: [backbone]
  epochs: 10

lr_scheduler:
  enable: True
  name: ReduceLROnPlateau
  factor: 0.1
  patience: 5
  min_lr: 0

clip_grad_norm_:
  enable: True
  max_norm: 10.0

trainer:
  epochs: 120
    
trainer_colab:
  epochs: 120


# note:
# mkdir -p /home/ubuntu/Documents/datasets/ppe/raw && cp /content/drive/My\ Drive/Private_Datasets/ppe.zip /home/ubuntu/Documents/datasets/ppe/raw/

