base: config/base_epoch.yml

model:
  backbone: resnet50
  pooling: gem_pooling
  head: BNHead
  bn_where: after

data:
  name: peta
  batch_size: 32

optimizer:
  name: adam
  lr: 0.00035

loss:
  name: CEL_Sigmoid

freeze:
  enable: True
  layers: [backbone]
  epochs: 10

lr_scheduler:
  enable: True
  name: WarmupMultiStepLR
  steps: [30, 60, 90]
  gamma: 0.1
  warmup_factor: 0.01
  warmup_iters: 10

# clipping gradient
clip_grad_norm_:
  enable: True
  max_norm: 10.0

trainer:
  epochs: 120
  
trainer_colab:
  epochs: 120