# resume: "/content/drive/Shared drives/REID/HIEN/Models/OSNet_Person_Attribute_Refactor/checkpoints/0731_232453/model_best_accuracy.pth"
resume: 'model_best_accuracy.pth'

n_gpu: 0

model:
  name: baseline
  backbone: resnet50
  pretrained: False
  pooling: gem_pooling
  pooling_size: 1
  head: BNHead
  bn_where: after
  batch_norm_bias: True
  use_tqdm: False

data:
  size: [256, 192]
  # pickle file, list of attribute saved in here. get it from datasource.saved_attribute()
  path_attribute: peta_attribute.pkl