base: config/base_epoch.yml

model:
  backbone: resnet50
  pooling: gem_pooling
  head: BNHead
  bn_where: after

data:
  name: peta
  batch_size: 64

optimizer:
  name: sgd
  lr: 0.01
  specified_lr:
    enable: True
    lr: 0.1
    layers: [head]

loss:
  name: CEL_Sigmoid

freeze:
  enable: True
  layers: [backbone]
  epochs: 10

lr_scheduler:
  enable: True
  name: MultiStepLR
  steps: [20, 40, 60, 80, 100]
  gamma: 0.1

# clipping gradient
clip_grad_norm_:
  enable: True
  max_norm: 10.0

trainer:
  epochs: 120
  
trainer_colab:
  epochs: 120