model:
  backbone: resnet50
  pooling: gem_pooling
  head: BNHead
  bn_where: after

data:
  name: pa_100k
  batch_size: 32

optimizer:
  name: adam
  lr: 0.00035

freeze:
  enable: True
  layers: [backbone]
  epochs: 10

loss:
  name: CEL_Sigmoid

lr_scheduler:
  enable: True
  name: WarmupCosineAnnealingLR
  eta_min_lr: 0.00000077

trainer:
  epochs: 120
  
trainer_colab:
  epochs: 120