model:
  backbone: resnet50
  pooling: gem_pooling
  head: BNHead
  bn_where: after

data:
  name: ppe_two
  batch_size: 16

optimizer:
  name: adam
  lr: 0.00035

loss:
  name: CEL_Sigmoid

lr_scheduler:
  enable: True
  name: WarmupMultiStepLR
  steps: [30, 40, 50]
  gamma: 0.1
  warmup_factor: 0.01
  warmup_iters: 10


trainer:
  epochs: 60
    
trainer_colab:
  epochs: 60