base: config/base_episode.yml

model:
  backbone: resnet50
  pooling: gem_pooling
  head: BNHead
  bn_where: after

data:
  name: peta
  train:
    num_attribute: 16
    num_instance: 4
    num_iterator: 700
    selected_ratio: 0.5
  val:
    num_attribute: 16
    num_instance: 4
    num_iterator: 100
    selected_ratio: 0.5

optimizer:
  name: sgd
  lr: 0.01
  specified_lr:
    enable: True
    lr: 0.1
    layers: [head]

loss:
  name: Singular_BCE
  reduction: mean

freeze:
  enable: True
  layers: [backbone]
  epochs: 10

lr_scheduler:
  enable: True
  name: ReduceLROnPlateau
  factor: 0.1
  patience: 5
  min_lr: 0.00000001

# clipping gradient
clip_grad_norm_:
  enable: True
  max_norm: 10.0

trainer:
  epochs: 80
    
trainer_colab:
  epochs: 80

# note:
# mkdir -p /home/ubuntu/Documents/datasets/ppe/raw && cp /content/drive/My\ Drive/Private_Datasets/ppe.zip /home/ubuntu/Documents/datasets/ppe/raw/

