model:
  backbone: resnet50
  pooling: gem_pooling
  head: BNHead
  bn_where: after

data:
  name: pa_100k
  batch_size: 64

loss:
  name: CEL_Sigmoid

freeze:
  enable: True
  layers: [backbone]
  epochs: 10

lr_scheduler:
  enable: True
  name: WarmupCosineAnnealingLR
  delay_iters: 20
  eta_min_lr: 7.7e-07
  warmup_factor: 0.01
  warmup_iters: 10

trainer:
  epochs: 50
  
trainer_colab:
  epochs: 50