base: config/base_epoch.yml

model:
  backbone: osnet
  pooling: gem_pooling
  head: ReductionHead
  bn_where: before
  batch_norm_bias: True

data:
  name: peta

optimizer:
  name: adam
  lr: 0.00035

loss:
  name: Non_BCEWithLogitsLoss

lr_scheduler:
  enable: True
  name: WarmupCosineAnnealingLR
  delay_iters: 30

trainer:
  epochs: 120
  
trainer_colab:
  epochs: 120