base: config/base_epoch.yml

model:
  backbone: osnet
  pooling: gem_pooling
  head: ReductionHead
  bn_where: before

data:
  name: pa_100k
  image_size: [256, 128]

optimizer:
  name: adam
  lr: 0.00035

loss:
  name: CEL_Sigmoid

lr_scheduler:
  enable: True
  name: WarmupCosineAnnealingLR
  delay_iters: 30

trainer:
  epochs: 120
  
trainer_colab:
  epochs: 120