model:
  backbone: resnet50
  pooling: gem_pooling
  head: BNHead
  bn_where: after
  batch_norm_bias: True

data:
  name: peta

loss:
  name: Non_BCEWithLogitsLoss

freeze:
  enable: True
  layers: [backbone]
  epochs: 10

lr_scheduler:
  enable: True
  name: WarmupCosineAnnealingLR

trainer:
  epochs: 120
  
trainer_colab:
  epochs: 120