base: config/base_epoch.yml

model:
  backbone: resnet50
  pooling: gem_pooling
  head: BNHead
  bn_where: after

data:
  name: peta
  image_size: [256, 192]
  batch_size: 64

optimizer:
  name: adam
  lr: 0.00035

loss:
  name: CEL_Sigmoid

freeze:
  enable: False
  layers: [backbone]
  epochs: 10

lr_scheduler:
  enable: True
  MultiStepLR:
  steps: [15, 20, 25]
  gamma: 0.1

trainer:
  epochs: 30
  
trainer_colab:
  epochs: 30

