base: config/base_epoch.yml

model:
  backbone: resnet50
  pooling: gem_pooling
  head: BNHead
  bn_where: after

data:
  name: peta
  image_size: [256, 192]
  batch_size: 32

optimizer:
  name: adam
  lr: 0.00035

loss:
  name: FocalLoss

freeze:
  enable: True
  layers: [backbone]
  epochs: 10

lr_scheduler:
  enable: True
  name: CosineAnnealingLR
  max_iters: 120
  eta_min_lr: 0

trainer:
  epochs: 120
  
trainer_colab:
  epochs: 120
