base: config/base_episode.yml

model:
  backbone: resnet50
  pooling: avg_pooling
  head: BNHead
  bn_where: after

data:
  name: peta
  num_workers: 4
  pin_memory: True
  train:
    num_attribute: 4
    num_instance: 16
    num_iterator: 300
    selected_ratio: 0.5
  val:
    num_attribute: 4
    num_instance: 16
    num_iterator: 100
    selected_ratio: 0.5

optimizer:
  name: adam
  lr: 0.00035

loss:
  name: Singular_BCE

freeze:
  enable: True
  layers: [backbone]
  epochs: 10

lr_scheduler:
  enable: True
  name: WarmupMultiStepLR
  steps: [30, 60, 90]
  gamma: 0.1
  warmup_factor: 0.01
  warmup_iters: 10

trainer:
  n_gpu: 1
  epochs: 120
    
trainer_colab:
  epochs: 120

# note:
# mkdir -p /home/ubuntu/Documents/datasets/ppe/raw && cp /content/drive/My\ Drive/Private_Datasets/ppe.zip /home/ubuntu/Documents/datasets/ppe/raw/
