base: config/base_epoch.yml

model:
  backbone: resnet50
  pooling: gem_pooling
  head: BNHead
  bn_where: after

data:
  name: peta
  image_size: [256, 192]
  batch_size: 64

optimizer:
  name: sgd
  lr: 0.01
  specified_lr:
    enable: True
    lr: 0.1
    layers: [head]

loss:
  name: CEL_Sigmoid

freeze:
  enable: True
  layers: [backbone]
  epochs: 10

lr_scheduler:
  enable: True
  name: WarmupCosineAnnealingLR
  max_iters: 120
  delay_iters: 25
  eta_min_lr: 0
  warmup_factor: 0.01
  warmup_iters: 10

clip_grad_norm_:
  enable: True
  max_norm: 10.0

trainer:
  epochs: 120
  
trainer_colab:
  epochs: 120